# travis build and test config
language: csharp
dotnet: 5.0.100
mono: none
os: linux
dist: bionic

branches:
  only:
    - master
    - develop
    - hotfix/*

before_install:
  - dotnet tool install Cake.Tool --tool-path ./tools

script:
  - ./tools/dotnet-cake -target=test -config=debug
