# Build and Test withc Azure Pipelines
trigger:
- master
- release/*
- hotfix/*

pool:
  vmImage: Ubuntu-18.04

stages:
  - stage: Install Dependencies
    jobs:
      - job: SDK
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 5.x
      - job: Cake
        steps:
          - script: dotnet tool install Cake.Tool --tool-path ./tools
  - stage: Build and Test
    jobs:
      - job: Cake
        steps:
          - script: ./tools/dotnet-cake -target=test -config=debug
