# Build and Test with Azure Pipelines

trigger:
- master
- release/*
- hotfix/*

pool:
  vmImage: Ubuntu-18.04

name: Build_and_Test

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 5.x
  - script: dotnet tool install Cake.Tool --tool-path ./tools
  - script: ./tools/dotnet-cake -target=test -config=debug
