# Dependency Management with Dependabot

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Europe/Berlin"

